# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WeatherGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_MainWindow(object):

    def loadData(self):
        connection = sqlite3.connect('Weather')
        query = "SELECT * FROM weatherData"
        result = connection.execute(query)
        self.tbl.setRowCount(0)
       
        for rowNum, rowData in enumerate(result):
            self.tbl.insertRow(rowNum)
            for colNum, colData in enumerate(rowData):
                self.tbl.setItem(rowNum, colNum, QtWidgets.QTableWidgetItem(str(colData)))

        
        cur = connection.cursor()
        info = "2018-04-22 00:00:00"
        query1 = """SELECT * FROM weatherData WHERE date = ?"""
        cur.execute(query1, (info,))
        dateDetails = cur.fetchall()

        for row in dateDetails:
            self.txtDate.setText(str(row[0]))
            self.txtHeat.setText(str(row[1]))
            self.txtRain.setText(str(row[2]))
            self.txtTemp.setText(str(row[3]))

        connection.close()




    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 829)
        MainWindow.setAutoFillBackground(True)

        MainWindow.setStyleSheet("background-color: #f9dea7;")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(110, 30, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAutoFillBackground(False)
        self.lblTitle.setTextFormat(QtCore.Qt.PlainText)
        self.lblTitle.setWordWrap(False)
        self.lblTitle.setObjectName("lblTitle")
        self.lblLocation = QtWidgets.QLabel(self.centralwidget)
        self.lblLocation.setGeometry(QtCore.QRect(30, 80, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblLocation.setFont(font)
        self.lblLocation.setObjectName("lblLocation")
        self.lblDate = QtWidgets.QLabel(self.centralwidget)
        self.lblDate.setGeometry(QtCore.QRect(30, 160, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lblDate.setFont(font)
        self.lblDate.setObjectName("lblDate")
        self.txtDate = QtWidgets.QLabel(self.centralwidget)
        self.txtDate.setGeometry(QtCore.QRect(220, 140, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.txtDate.setFont(font)
        self.txtDate.setText("")
        self.txtDate.setObjectName("txtDate")
        self.lblHeat = QtWidgets.QLabel(self.centralwidget)
        self.lblHeat.setGeometry(QtCore.QRect(30, 200, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lblHeat.setFont(font)
        self.lblHeat.setObjectName("lblHeat")
        self.txtHeat = QtWidgets.QLabel(self.centralwidget)
        self.txtHeat.setGeometry(QtCore.QRect(220, 190, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.txtHeat.setFont(font)
        self.txtHeat.setText("")
        self.txtHeat.setObjectName("txtHeat")
        self.lblRain = QtWidgets.QLabel(self.centralwidget)
        self.lblRain.setGeometry(QtCore.QRect(30, 250, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lblRain.setFont(font)
        self.lblRain.setObjectName("lblRain")
        self.txtRain = QtWidgets.QLabel(self.centralwidget)
        self.txtRain.setGeometry(QtCore.QRect(220, 240, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.txtRain.setFont(font)
        self.txtRain.setText("")
        self.txtRain.setObjectName("txtRain")
        self.lblTemp = QtWidgets.QLabel(self.centralwidget)
        self.lblTemp.setGeometry(QtCore.QRect(30, 290, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lblTemp.setFont(font)
        self.lblTemp.setObjectName("lblTemp")
        self.txtTemp = QtWidgets.QLabel(self.centralwidget)
        self.txtTemp.setGeometry(QtCore.QRect(220, 280, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.txtTemp.setFont(font)
        self.txtTemp.setText("")
        self.txtTemp.setObjectName("txtTemp")
        self.tbl = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl.setGeometry(QtCore.QRect(0, 450, 521, 271))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 198, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 244, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 221, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 99, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 132, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 198, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 226, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 198, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 244, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 221, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 99, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 132, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 198, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 226, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 99, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 198, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 244, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 221, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 99, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 132, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 99, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(124, 99, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 198, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 198, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 198, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tbl.setPalette(palette)
        self.tbl.setAutoFillBackground(False)
        self.tbl.setShowGrid(True)
        self.tbl.setGridStyle(QtCore.Qt.DotLine)
        self.tbl.setWordWrap(True)
        self.tbl.setCornerButtonEnabled(True)
        self.tbl.setRowCount(8)
        self.tbl.setColumnCount(5)
        self.tbl.setObjectName("tbl")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(160, 740, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnLoad.setFont(font)
        self.btnLoad.setObjectName("btnLoad")

        self.btnLoad.clicked.connect(self.loadData)
        # self.btnLoad.clicked.connect(self.clickLoad)
        # self.btnLoad.clicked.connect(self.insertDate)


        self.lblSevenDay = QtWidgets.QLabel(self.centralwidget)
        self.lblSevenDay.setGeometry(QtCore.QRect(150, 400, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblSevenDay.setFont(font)
        self.lblSevenDay.setAutoFillBackground(False)
        self.lblSevenDay.setTextFormat(QtCore.Qt.PlainText)
        self.lblSevenDay.setWordWrap(False)
        self.lblSevenDay.setObjectName("lblSevenDay")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-270, -50, 1061, 951))
        self.label.setStyleSheet("image: url(:/newPrefix/bg.webp);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lblDay = QtWidgets.QLabel(self.centralwidget)
        self.lblDay.setGeometry(QtCore.QRect(400, 80, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(False)
        font.setUnderline(True)
        self.lblDay.setFont(font)
        self.lblDay.setText("")
        self.lblDay.setObjectName("lblDay")
        self.label.raise_()
        self.lblTitle.raise_()
        self.lblLocation.raise_()
        self.lblDate.raise_()
        self.txtDate.raise_()
        self.lblHeat.raise_()
        self.txtHeat.raise_()
        self.lblRain.raise_()
        self.txtRain.raise_()
        self.lblTemp.raise_()
        self.txtTemp.raise_()
        self.tbl.raise_()
        self.btnLoad.raise_()
        self.lblSevenDay.raise_()
        self.lblDay.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTitle.setText(_translate("MainWindow", "Weather of the Day"))
        self.lblLocation.setText(_translate("MainWindow", "Marikina"))
        self.lblDate.setText(_translate("MainWindow", "Date: "))
        self.lblHeat.setText(_translate("MainWindow", "Heat Index:"))
        self.lblRain.setText(_translate("MainWindow", "Rainfall:"))
        self.lblTemp.setText(_translate("MainWindow", "Temperature:"))
        self.btnLoad.setText(_translate("MainWindow", "Load"))
        self.lblSevenDay.setText(_translate("MainWindow", "7-Day Forecast"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

